# Application
spring.application.name=project
server.port=8080

# Error
server.error.include-stacktrace=never
server.error.include-message=always
server.error.include-binding-errors=always

# Redis
spring.data.redis.repositories.enabled=false
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/bootcamp
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Kafka
spring.kafka.bootstrap-servers=localhost:9092

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Logging
logging.pattern.console=%d{HH:mm:ss} [%thread{id}] [%-5p]%c{0}- %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n

logging.file.name=log/application.log

# Log Level
logging.level.root=INFO
logging.level.com.bootcamp=DEBUG

# Rolling File
logging.logback.rollingpolicy.max-file-size=1MB
logging.logback.rollingpolicy.file-name-pattern=log/application-%d{yyyy-MM-dd}.%i.log
logging.logback.rollingpolicy.max-history=5

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
springdoc.api-docs.enabled=true

# Scalar
springdoc.scalar.theme=deepSpace
springdoc.scalar.layout=modern
springdoc.scalar.documentDownloadType=both
springdoc.scalar.url=/api-docs
scalar.path=/docs
scalar.enabled=true